# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: pride-molecules-indexer-1.1.0dev
channels:
  - openms
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-argparser=0.7.1 # for argument parsing in our Rscripts
  - conda-forge::fonts-conda-ecosystem=1 # for the fonts in QC reports
  - conda-forge::python=3.9.4
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::pygments=2.9.0
  - bioconda::java-jdk
  - conda-forge::coreutils=8.31
  - conda-forge::pandoc=2.11.4 # had to downgrade because of errors with PTXQC (and its rmarkdown)